//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAuthentication_RoleBased_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int R_id { get; set; }
        public string R_Name { get; set; }
        public string R_FA { get; set; }
        public int R_Expense { get; set; }
        public string R_Head { get; set; }
    }
}
