//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAuthentication_RoleBased_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public object Role { get; internal set; }
        public int U_Id { get; set; }
        public string U_Name { get; set; }
        public string U_Pass { get; set; }
        public string U_Role { get; set; }
    }
}
